# Generated by Django 5.2.7 on 2025-10-15 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='Cliente Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('TRANSITO', 'transito'), ('ALISTAMIENTO', 'alistamiento'), ('POR_VERIFICAR', 'por_verificar'), ('VERIFICADO', 'verificado'), ('EMPACADO_POR_DESPACHAR', 'empacado_por_despachar'), ('DESPACHADO', 'despachado'), ('DESPACHADO_POR_FACTURAR', 'despachado_por_facturar'), ('ENTREGADO', 'entregado'), ('DEVUELTO', 'devuelto'), ('PRODUCCION', 'produccion'), ('BORDADO', 'bordado'), ('DROPSHIPPING', 'dropshipping'), ('COMPRA', 'compra'), ('ANULADO', 'anulado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fotos_abierto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fotos_cerrado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
